<?php


namespace Milestone\SS\ModelTraits;


trait PrintingDefaults
{

    static public $query1 = [
        'CR1' => 'SELECT R.docno,R.fycode,R.fncode,R.mode,R.date,R.amount,U.name customer FROM receipts R,users U WHERE U.id = R.customer AND _ref = ?',
        'BR1' => 'SELECT R.docno,R.fycode,R.fncode,R.mode,R.date,R.amount,R.bank,R.cheque,R.cheque_date,U.name customer FROM receipts R,users U WHERE U.id = R.customer AND _ref = ?',
        'BR2' => 'SELECT R.docno,R.fycode,R.fncode,R.mode,R.date,R.amount,R.bank,R.cheque,R.cheque_date,U.name customer FROM receipts R,users U WHERE U.id = R.customer AND _ref = ?',
        'MT2' => 'SELECT E.name executive, S.name store, T.docno, T.date, P.narration product, TD.quantity, TD.rate, TD.tax, (TD.discount01+TD.discount02) discount, (((TD.quantity*TD.rate)-TD.discount01)+(((TD.quantity*TD.rate)-TD.discount01)*TD.tax/100)-TD.discount02) total FROM transactions T, transaction_details TD, users E, stores S, products P WHERE TD.`transaction` = T._ref AND T.user = E.id AND S.id = T.store AND P.id = TD.product AND T._ref = ?',
        'MT1' => 'SELECT E.name executive, S.name store, T.docno, T.date, P.narration product, TD.quantity, (SELECT quantity FROM transaction_details WHERE `transaction` = ? AND product = TD.product LIMIT 0,1) actual, TD.rate, TD.tax, (TD.discount01+TD.discount02) discount, (((TD.quantity*TD.rate)-TD.discount01)+(((TD.quantity*TD.rate)-TD.discount01)*TD.tax/100)-TD.discount02) total FROM transactions T, transaction_details TD, users E, stores S, products P WHERE TD.`transaction` = T._ref AND T.user = E.id AND S.id = T.store AND P.id = TD.product AND T._ref = ?',
        'SL1' => 'SELECT E.`name` executive, S.`name` store, CASE WHEN C.`name` IS NULL THEN \'CASH SALE\' ELSE C.`name` END customer, docno, `date`, P.narration product, quantity, rate, tax, (discount01+discount02) discount, (((quantity*rate)-discount01)+(((quantity*rate)-discount01)*tax/100)-discount02) total FROM transaction_details TD LEFT JOIN `transactions` T ON T._ref = TD.`transaction` LEFT JOIN `users` E ON T.`user` = E.id LEFT JOIN stores S ON S.id = T.store LEFT JOIN products P ON P.id = TD.product LEFT JOIN `users` C ON C.id = T.customer WHERE T.fncode LIKE \'SL%\' AND T._ref = ?',
        'SL2' => 'SELECT E.`name` executive, S.`name` store, CASE WHEN C.`name` IS NULL THEN \'CASH SALE\' ELSE C.`name` END customer, docno, `date`, P.narration product, quantity, rate, tax, (discount01+discount02) discount, (((quantity*rate)-discount01)+(((quantity*rate)-discount01)*tax/100)-discount02) total FROM transaction_details TD LEFT JOIN `transactions` T ON T._ref = TD.`transaction` LEFT JOIN `users` E ON T.`user` = E.id LEFT JOIN stores S ON S.id = T.store LEFT JOIN products P ON P.id = TD.product LEFT JOIN `users` C ON C.id = T.customer WHERE T.fncode LIKE \'SL%\' AND T._ref = ?',
        'SL3' => 'SELECT E.`name` executive, S.`name` store, CASE WHEN C.`name` IS NULL THEN \'CASH SALE\' ELSE C.`name` END customer, docno, `date`, P.narration product, quantity, rate, tax, (discount01+discount02) discount, (((quantity*rate)-discount01)+(((quantity*rate)-discount01)*tax/100)-discount02) total FROM transaction_details TD LEFT JOIN `transactions` T ON T._ref = TD.`transaction` LEFT JOIN `users` E ON T.`user` = E.id LEFT JOIN stores S ON S.id = T.store LEFT JOIN products P ON P.id = TD.product LEFT JOIN `users` C ON C.id = T.customer WHERE T.fncode LIKE \'SL%\' AND T._ref = ?',
        'SL4' => 'SELECT E.`name` executive, S.`name` store, CASE WHEN C.`name` IS NULL THEN \'CASH SALE\' ELSE C.`name` END customer, docno, `date`, P.narration product, quantity, rate, tax, (discount01+discount02) discount, (((quantity*rate)-discount01)+(((quantity*rate)-discount01)*tax/100)-discount02) total FROM transaction_details TD LEFT JOIN `transactions` T ON T._ref = TD.`transaction` LEFT JOIN `users` E ON T.`user` = E.id LEFT JOIN stores S ON S.id = T.store LEFT JOIN products P ON P.id = TD.product LEFT JOIN `users` C ON C.id = T.customer WHERE T.fncode LIKE \'SL%\' AND T._ref = ?',
        'SL5' => 'SELECT E.`name` executive, S.`name` store, CASE WHEN C.`name` IS NULL THEN \'CASH SALE\' ELSE C.`name` END customer, docno, `date`, P.narration product, quantity, rate, tax, (discount01+discount02) discount, (((quantity*rate)-discount01)+(((quantity*rate)-discount01)*tax/100)-discount02) total FROM transaction_details TD LEFT JOIN `transactions` T ON T._ref = TD.`transaction` LEFT JOIN `users` E ON T.`user` = E.id LEFT JOIN stores S ON S.id = T.store LEFT JOIN products P ON P.id = TD.product LEFT JOIN `users` C ON C.id = T.customer WHERE T.fncode LIKE \'SL%\' AND T._ref = ?',
        'SO1' => 'SELECT E.name executive, S.name store, C.name customer, docno, `date`, P.narration product, quantity, rate, tax, (discount01+discount02) discount, (((quantity*rate)-discount01)+(((quantity*rate)-discount01)*tax/100)-discount02) total FROM sales_order SO, sales_order_items SOI, users E, stores S, products P, users C WHERE SOI.`so` = SO._ref AND SO.user = E.id AND S.id = SO.store AND P.id = SOI.product AND C.id = SO.customer AND SO._ref = ?',
        'SO2' => 'SELECT E.name executive, S.name store, C.name customer, docno, `date`, P.narration product, quantity, rate, tax, (discount01+discount02) discount, (((quantity*rate)-discount01)+(((quantity*rate)-discount01)*tax/100)-discount02) total FROM sales_order SO, sales_order_items SOI, users E, stores S, products P, users C WHERE SOI.`so` = SO._ref AND SO.user = E.id AND S.id = SO.store AND P.id = SOI.product AND C.id = SO.customer AND SO._ref = ?',
    ];

    static public $query1_props = [
        'CR1' => '_ref',
        'BR1' => '_ref',
        'BR2' => '_ref',
        'MT2' => '_ref',
        'MT1' => 'id,_ref',
        'SL1' => '_ref',
        'SL2' => '_ref',
        'SL3' => '_ref',
        'SL4' => '_ref',
        'SL5' => '_ref',
        'SO1' => '_ref',
        'SO2' => '_ref',
    ];

    static public $template = [
        'CR1' => "[{type:`RAW`,detail:`[company.print_line1]`,align:`center`,bold:true},{type:`feed`,amount:1},{type:`RAW`,detail:`[this.header1]`,align:`center`,underline:true},{type:`wide`,source:`[this.query1]`,title:`['CUSTOMER']`,detail:`customer`},{type:`wide`,source:`[this.query1]`,title:`['DOCNO']`,detail:`docno`},{type:`wide`,source:`[this.query1]`,title:`['DATE']`,detail:`[__.docdate(data.date)]`},{type:`feed`,amount:1},{type:`RAW`,source:`[this.query1]`,detail:`[__.amount(data.amount)]`,size:1,bold:true,align:`center`},{type:`feed`,amount:2},{type:`line`},{type:`RAW`,detail:`[this.footer1]`,align:`center`}]",
        'BR1' => "[{type:`RAW`,detail:`[company.print_line1]`,align:`center`,bold:true},{type:`feed`,amount:1},{type:`RAW`,detail:`[this.header1]`,align:`center`,underline:true},{type:`wide`,source:`[this.query1]`,title:`['CUSTOMER']`,detail:`customer`},{type:`wide`,source:`[this.query1]`,title:`['DOCNO']`,detail:`docno`},{type:`wide`,source:`[this.query1]`,title:`['DATE']`,detail:`[__.docdate(data.date)]`},{type:`feed`,amount:1},{type:`RAW`,source:`[this.query1]`,detail:`[__.amount(data.amount)]`,size:1,bold:true,align:`center`},{type:`feed`,amount:1},{type:`wide`,source:`[this.query1]`,title:`['Cheque']`,detail:`[data.cheque]`},{type:`wide`,source:`[this.query1]`,title:`['Date']`,detail:`[__.docdate(data.cheque_date)]`},{type:`wide`,source:`[this.query1]`,title:`['Bank']`,detail:`[data.bank]`},{type:`line`},{type:`RAW`,detail:`[this.footer1]`,align:`center`}]",
        'BR2' => "[{type:`RAW`,detail:`[company.print_line1]`,align:`center`,bold:true},{type:`feed`,amount:1},{type:`RAW`,detail:`[this.header1]`,align:`center`,underline:true},{type:`wide`,source:`[this.query1]`,title:`['CUSTOMER']`,detail:`customer`},{type:`wide`,source:`[this.query1]`,title:`['DOCNO']`,detail:`docno`},{type:`wide`,source:`[this.query1]`,title:`['DATE']`,detail:`[__.docdate(data.date)]`},{type:`feed`,amount:1},{type:`RAW`,source:`[this.query1]`,detail:`[__.amount(data.amount)]`,size:1,bold:true,align:`center`},{type:`wide`,source:`[this.query1]`,title:`['Cheque']`,detail:`[data.cheque]`,on:`data.cheque`},{type:`wide`,source:`[this.query1]`,title:`['Date']`,detail:`[__.docdate(data.cheque_date)]`,on:`data.cheque_date`},{type:`wide`,source:`[this.query1]`,title:`['Bank']`,detail:`[data.bank]`,on:`data.bank`},{type:`feed`,amount:1},{type:`line`},{type:`RAW`,detail:`[this.footer1]`,align:`center`}]",
        'MT2' => "[{type:`RAW`,detail:`[company.print_line1]`,align:`center`,bold:true},{type:`feed`,amount:1},{type:`RAW`,detail:`[this.header1]`,align:`center`,underline:true},{type:`wide`,title:`['STORE']`,detail:`[this.query1[0].store]`},{type:`wide`,title:`['DATE']`,detail:`[__.docdate(this.query1[0].date)]`},{type:`wide`,title:`['DOCNO']`,detail:`[this.query1[0].docno]`},{type:`feed`,amount:1},{type:`wide`,title:`['EXECUTIVE']`,detail:`[this.query1[0].executive]`},{type:`feed`,amount:1},{type:`table`,source:`[this.query1]`,columns:[`No`,`Item`,`Qty`],width:[1,5,2],keys:[`[AI]`,`product`,`[__.quantity(data.quantity)]`]},{type:`wide`,title:`['Items']`,detail:`[this.query1.length]`,},{type:`wide`,title:`['Quantity']`,detail:`[__.quantity(_.sumBy(this.query1,({ quantity }) => _.toNumber(quantity)))]`},{type:`wide`,title:`['Value']`,detail:`[__.amount(_.sumBy(this.query1,'total'))]`}]",
        'MT1' => "[{type:`RAW`,detail:`[company.print_line1]`,align:`center`,bold:true},{type:`feed`,amount:1},{type:`RAW`,detail:`[this.header1]`,align:`center`,underline:true},{type:`wide`,title:`['STORE']`,detail:`[this.query1[0].store]`},{type:`wide`,title:`['DATE']`,detail:`[__.docdate(this.query1[0].date)]`},{type:`wide`,title:`['DOCNO']`,detail:`[this.query1[0].docno]`},{type:`feed`,amount:1},{type:`wide`,title:`['EXECUTIVE']`,detail:`[this.query1[0].executive]`},{type:`feed`,amount:1},{type:`table`,source:`[this.query1]`,columns:[`No`,`Item`,`Out`,`In`],width:[1,8,2,2],keys:[`[AI]`,`product`,`[__.quantity(data.actual)]`,`[__.quantity(data.quantity)]`]},{type:`wide`,title:`['Items']`,detail:`[this.query1.length]`,},{type:`wide`,title:`['In Qty']`,detail:`[__.quantity(_.sumBy(this.query1,({ quantity }) => _.toNumber(quantity)))]`},{type:`wide`,title:`['Value']`,detail:`[__.amount(_.sumBy(this.query1,'total'))]`}]",
        'SL1' => "[{type:`RAW`,detail:`[company.print_line1]`,align:`center`,bold:true},{type:`feed`,amount:1},{type:`RAW`,detail:`[this.header1]`,align:`center`,underline:true},{type:`wide`,title:`['DATE']`,detail:`[__.docdate(this.query1[0].date)]`},{type:`wide`,title:`['DOCNO']`,detail:`[this.query1[0].docno]`},{type:`feed`,amount:1},{type:`wide`,title:`['CUSTOMER']`,detail:`[this.query1[0].customer]`},{type:`feed`,amount:1},{type:`table`,source:`[this.query1]`,columns:[`No`,`Item`,`Qty`,`Total`],width:[1,11,3,4],keys:[`[AI]`,`[data.product+' @ Rate: ' + __.rate(data.rate)]`,`[__.quantity(data.quantity)]`,`[__.amount(data.total)]`]},{type:`wide`,title:`['Total Items']`,detail:`[this.query1.length]`,},{type:`wide`,title:`['Discount']`,detail:`[__.amount(_.sumBy(this.query1,'discount'))]`},{type:`wide`,title:`['Tax']`,detail:`[__.amount(_.sumBy(this.query1,({ tax }) => _.toNumber(tax)))]`},{type:`stack`,title:`['PAYABLE']`,detail:`[__.amount(_.sumBy(this.query1,'total'))]`,align:`center`,detail_size:1,detail_bold:true,title_bold:false},{type:`line`},{type:`raw`,align:`center`,detail:`[this.footer1]`}]",
        'SL2' => "[{type:`RAW`,detail:`[company.print_line1]`,align:`center`,bold:true},{type:`feed`,amount:1},{type:`RAW`,detail:`[this.header1]`,align:`center`,underline:true},{type:`wide`,title:`['DATE']`,detail:`[__.docdate(this.query1[0].date)]`},{type:`wide`,title:`['DOCNO']`,detail:`[this.query1[0].docno]`},{type:`feed`,amount:1},{type:`wide`,title:`['CUSTOMER']`,detail:`[this.query1[0].customer]`},{type:`feed`,amount:1},{type:`table`,source:`[this.query1]`,columns:[`No`,`Item`,`Qty`,`Total`],width:[1,11,3,4],keys:[`[AI]`,`[data.product+' @ Rate: ' + __.rate(data.rate)]`,`[__.quantity(data.quantity)]`,`[__.amount(data.total)]`]},{type:`wide`,title:`['Total Items']`,detail:`[this.query1.length]`,},{type:`wide`,title:`['Discount']`,detail:`[__.amount(_.sumBy(this.query1,'discount'))]`},{type:`wide`,title:`['Tax']`,detail:`[__.amount(_.sumBy(this.query1,({ tax }) => _.toNumber(tax)))]`},{type:`stack`,title:`['PAYABLE']`,detail:`[__.amount(_.sumBy(this.query1,'total'))]`,align:`center`,detail_size:1,detail_bold:true,title_bold:false},{type:`line`},{type:`raw`,align:`center`,detail:`[this.footer1]`}]",
        'SL3' => "[{type:`RAW`,detail:`[company.print_line1]`,align:`center`,bold:true},{type:`feed`,amount:1},{type:`RAW`,detail:`[this.header1]`,align:`center`,underline:true},{type:`wide`,title:`['DATE']`,detail:`[__.docdate(this.query1[0].date)]`},{type:`wide`,title:`['DOCNO']`,detail:`[this.query1[0].docno]`},{type:`feed`,amount:1},{type:`wide`,title:`['CUSTOMER']`,detail:`[this.query1[0].customer]`},{type:`feed`,amount:1},{type:`table`,source:`[this.query1]`,columns:[`No`,`Item`,`Qty`,`Total`],width:[1,11,3,4],keys:[`[AI]`,`[data.product+' @ Rate: ' + __.rate(data.rate)]`,`[__.quantity(data.quantity)]`,`[__.amount(data.total)]`]},{type:`wide`,title:`['Total Items']`,detail:`[this.query1.length]`,},{type:`wide`,title:`['Discount']`,detail:`[__.amount(_.sumBy(this.query1,'discount'))]`},{type:`wide`,title:`['Tax']`,detail:`[__.amount(_.sumBy(this.query1,({ tax }) => _.toNumber(tax)))]`},{type:`stack`,title:`['PAYABLE']`,detail:`[__.amount(_.sumBy(this.query1,'total'))]`,align:`center`,detail_size:1,detail_bold:true,title_bold:false},{type:`line`},{type:`raw`,align:`center`,detail:`[this.footer1]`}]",
        'SL4' => "[{type:`RAW`,detail:`[company.print_line1]`,align:`center`,bold:true},{type:`feed`,amount:1},{type:`RAW`,detail:`[this.header1]`,align:`center`,underline:true},{type:`wide`,title:`['DATE']`,detail:`[__.docdate(this.query1[0].date)]`},{type:`wide`,title:`['DOCNO']`,detail:`[this.query1[0].docno]`},{type:`feed`,amount:1},{type:`wide`,title:`['CUSTOMER']`,detail:`[this.query1[0].customer]`},{type:`feed`,amount:1},{type:`table`,source:`[this.query1]`,columns:[`No`,`Item`,`Qty`,`Total`],width:[1,11,3,4],keys:[`[AI]`,`[data.product+' @ Rate: ' + __.rate(data.rate)]`,`[__.quantity(data.quantity)]`,`[__.amount(data.total)]`]},{type:`wide`,title:`['Total Items']`,detail:`[this.query1.length]`,},{type:`wide`,title:`['Discount']`,detail:`[__.amount(_.sumBy(this.query1,'discount'))]`},{type:`wide`,title:`['Tax']`,detail:`[__.amount(_.sumBy(this.query1,({ tax }) => _.toNumber(tax)))]`},{type:`stack`,title:`['PAYABLE']`,detail:`[__.amount(_.sumBy(this.query1,'total'))]`,align:`center`,detail_size:1,detail_bold:true,title_bold:false},{type:`line`},{type:`raw`,align:`center`,detail:`[this.footer1]`}]",
        'SL5' => "[{type:`RAW`,detail:`[company.print_line1]`,align:`center`,bold:true},{type:`feed`,amount:1},{type:`RAW`,detail:`[this.header1]`,align:`center`,underline:true},{type:`wide`,title:`['DATE']`,detail:`[__.docdate(this.query1[0].date)]`},{type:`wide`,title:`['DOCNO']`,detail:`[this.query1[0].docno]`},{type:`feed`,amount:1},{type:`wide`,title:`['CUSTOMER']`,detail:`[this.query1[0].customer]`},{type:`feed`,amount:1},{type:`table`,source:`[this.query1]`,columns:[`No`,`Item`,`Qty`,`Total`],width:[1,11,3,4],keys:[`[AI]`,`[data.product+' @ Rate: ' + __.rate(data.rate)]`,`[__.quantity(data.quantity)]`,`[__.amount(data.total)]`]},{type:`wide`,title:`['Total Items']`,detail:`[this.query1.length]`,},{type:`wide`,title:`['Discount']`,detail:`[__.amount(_.sumBy(this.query1,'discount'))]`},{type:`wide`,title:`['Tax']`,detail:`[__.amount(_.sumBy(this.query1,({ tax }) => _.toNumber(tax)))]`},{type:`stack`,title:`['PAYABLE']`,detail:`[__.amount(_.sumBy(this.query1,'total'))]`,align:`center`,detail_size:1,detail_bold:true,title_bold:false},{type:`line`},{type:`raw`,align:`center`,detail:`[this.footer1]`}]",
        'SO1' => "[{type:`RAW`,detail:`[company.print_line1]`,align:`center`,bold:true},{type:`feed`,amount:1},{type:`RAW`,detail:`[this.header1]`,align:`center`,underline:true},{type:`wide`,title:`['DATE']`,detail:`[__.docdate(this.query1[0].date)]`},{type:`wide`,title:`['DOCNO']`,detail:`[this.query1[0].docno]`},{type:`feed`,amount:1},{type:`wide`,title:`['CUSTOMER']`,detail:`[this.query1[0].customer]`},{type:`feed`,amount:1},{type:`table`,source:`[this.query1]`,columns:[`No`,`Item`,`Qty`,`Total`],width:[1,11,3,4],keys:[`[AI]`,`[data.product+' @ Rate: ' + __.rate(data.rate)]`,`[__.quantity(data.quantity)]`,`[__.amount(data.total)]`]},{type:`wide`,title:`['Total Items']`,detail:`[this.query1.length]`,},{type:`wide`,title:`['Discount']`,detail:`[__.amount(_.sumBy(this.query1,'discount'))]`},{type:`wide`,title:`['Tax']`,detail:`[__.amount(_.sumBy(this.query1,({ tax }) => _.toNumber(tax)))]`},{type:`stack`,title:`['PAYABLE']`,detail:`[__.amount(_.sumBy(this.query1,'total'))]`,align:`center`,detail_size:1,detail_bold:true,title_bold:false},{type:`line`},{type:`raw`,align:`center`,detail:`[this.footer1]`}]",
        'SO2' => "[{type:`RAW`,detail:`[company.print_line1]`,align:`center`,bold:true},{type:`feed`,amount:1},{type:`RAW`,detail:`[this.header1]`,align:`center`,underline:true},{type:`wide`,title:`['DATE']`,detail:`[__.docdate(this.query1[0].date)]`},{type:`wide`,title:`['DOCNO']`,detail:`[this.query1[0].docno]`},{type:`feed`,amount:1},{type:`wide`,title:`['CUSTOMER']`,detail:`[this.query1[0].customer]`},{type:`feed`,amount:1},{type:`table`,source:`[this.query1]`,columns:[`No`,`Item`,`Qty`,`Total`],width:[1,11,3,4],keys:[`[AI]`,`[data.product+' @ Rate: ' + __.rate(data.rate)]`,`[__.quantity(data.quantity)]`,`[__.amount(data.total)]`]},{type:`wide`,title:`['Total Items']`,detail:`[this.query1.length]`,},{type:`wide`,title:`['Discount']`,detail:`[__.amount(_.sumBy(this.query1,'discount'))]`},{type:`wide`,title:`['Tax']`,detail:`[__.amount(_.sumBy(this.query1,({ tax }) => _.toNumber(tax)))]`},{type:`stack`,title:`['PAYABLE']`,detail:`[__.amount(_.sumBy(this.query1,'total'))]`,align:`center`,detail_size:1,detail_bold:true,title_bold:false},{type:`line`},{type:`raw`,align:`center`,detail:`[this.footer1]`}]",
    ];

    static public $object = [
    ];

    static public $query2 = [
    ];

    static public $query2_props = [
    ];

    static public $query3 = [
    ];

    static public $query3_props = [
    ];

}